import asyncio
import sys
import json
from app.services.agent_service import agent_service
from app.services.ai_service import ai_service
from app.config import settings

# Force UTF-8 stdout encoding on Windows
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

async def test_followup():
    print("=== Testing Web Research Multi-Turn Follow-Up Flow ===")
    print(f"Gemini API key status: {'Configured' if settings.GEMINI_API_KEY else 'NOT Configured'}")
    if not settings.GEMINI_API_KEY:
        print("Skipping test since GEMINI_API_KEY is not configured.")
        return
        
    # --- Turn 1: Research query ---
    turn1_user = "Research latest AI trends in 2026"
    print(f"\n[Turn 1 User]: {turn1_user}")
    
    intent = await agent_service.detect_task_intent(turn1_user)
    print(f"Detected Intent: {json.dumps(intent, indent=2)}")
    
    if intent and intent.get("agent") == "Research Agent":
        print("Executing Research Agent workflow...")
        # Execute workflow
        # Using a dummy user_id=1, we don't need a DB session for Research Agent as it doesn't write to SQL
        research_result = await agent_service.execute_workflow(user_id=1, intent=intent, db=None)
        turn1_ai = research_result["output"]
        print(f"\n[Turn 1 AI Response]:\n{turn1_ai}")
    else:
        print("Error: Turn 1 did not trigger the Research Agent!")
        return

    # --- Turn 2: Follow-up query ---
    turn2_user = "Summarize the AI trends you found in 5 points"
    print(f"\n[Turn 2 User]: {turn2_user}")
    
    intent2 = await agent_service.detect_task_intent(turn2_user)
    print(f"Detected Intent 2: {intent2} (Expected: None for standard chat)")
    
    # Prepare history & research context
    history = [
        {"sender": "user", "content": turn1_user},
        {"sender": "ai", "content": turn1_ai}
    ]
    
    research_context = ""
    if "🔍 **[Research Agent Active]**" in turn1_ai:
        research_context = turn1_ai

    print("\nCalling ai_service.generate_reply with history and active research context...")
    reply = await ai_service.generate_reply(
        companion_id="aria",
        message=turn2_user,
        history=history,
        temperature=0.3,
        tone="Analytical",
        rag_context="",
        emotion_modifier="",
        research_context=research_context
    )
    
    print(f"\n[Turn 2 AI Response]:\n{reply}")
    
    if "⚠️ **[SYSTEM NOTICE]**" in reply or "I've processed your query about" in reply:
        print("\n❌ Failure: Gemini API call failed or fell back to mock response.")
    else:
        print("\n✅ Success! The response was successfully generated by Gemini 2.5 and contains follow-up context.")

if __name__ == "__main__":
    asyncio.run(test_followup())
